export type UserRole = "customer" | "admin";
export type KYCStatus = "pending" | "verified" | "rejected";

export interface User {
  id: string; // from auth.uid
  email: string;
  name: string;
  role: UserRole;
  createdAt: string;
}

export interface Agency {
  id: string; // from auth.uid
  email: string;
  name: string;
  kycStatus: KYCStatus;
  contactNumber?: string;
  website?: string;
  createdAt: string;
}

export interface Package {
  id: string; // generated by firestore
  agencyId: string;
  destination: string;
  price: number;
  itinerary: string[]; // array of daily activities
  includedItems: {
    flights: boolean;
    hotels: boolean;
    meals: boolean;
    transfers: boolean;
  };
  createdAt: string;
  updatedAt: string;
}
